AMATH 584 Homework 3  
Kelton Busby

# Problem 1

In [58]:
import numpy as np
import os
import scipy.linalg as spl
from matplotlib import pyplot as plt

## Download datasets:

In [21]:
# Iterate through the original images folder finding all files
filelist=[]
for root, dirs, files in os.walk('C://Users//Kelton//UW//AMATH584//Homework//hw2/yalefaces/'):
    for file in files:
        #append the file name to the list
        filelist.append(os.path.join(root,file))
        
print('number of images:',len(filelist))

# Build a list of images from the files
images=[]
for imgfile in filelist:
    images.append(plt.imread(imgfile))

number of images: 165


In [16]:
# Iterate through the cropped images folder finding all files
filelist=[]
for root, dirs, files in os.walk('C:\\Users\\Kelton\\UW\\AMATH584\\Homework\\hw2\\yalefaces_cropped'):
    for file in files:
        #append the file name to the list
        filelist.append(os.path.join(root,file))
        
print('number of images:',len(filelist))

# Build a list of images from the files
cropped_images=[]
for imgfile in filelist:
    cropped_images.append(plt.imread(imgfile))

number of images: 272


## Modified Gram-Schmidt Orthogonalization Procedure

In [82]:
A = random.randn(25,20)

In [96]:
def modGramSchmidt(A):
    
    m,n = np.shape(A)
    Q = np.zeros([m,m])
    R = np.zeros([m,n])
    V = A.copy()
    
    
    '''Returns an orthogonalization of input matrix A using modified Gram-Schmidt algorithm.'''
    
    for i in np.arange(0,n):
        
        R[i,i] = spl.norm(V[:,0])
        Q[:,i]=V[:,i] / R[i,i]
        
        for j in np.arange(i+1,n):
            
            QH = np.array(np.matrix(Q).H)
            R[i,j] = np.dot(QH[:,i],V[:,j])
            V[:,j] = V[:,j] - np.dot(R[i,j],Q[:,i])            
        
    return Q,R
    

In [97]:
q,r = modGramSchmidt(A)

In [89]:
Q, R = spl.qr(A)

In [102]:
Q[0]

array([-4.64721926e-02,  1.20833087e-01, -5.28536020e-02,  3.68389065e-01,
       -1.58541453e-01,  1.52586089e-02,  6.23174703e-02, -7.53448458e-02,
       -2.50100377e-02, -2.82418334e-02, -2.10521856e-01,  1.10703255e-01,
       -2.76857255e-01,  5.12529212e-02, -2.44063652e-01,  4.30486821e-01,
       -1.54357119e-01,  4.98818038e-01,  2.38490392e-01,  1.98451598e-01,
       -1.17617760e-04, -2.24403621e-01, -7.46790742e-02,  5.16630388e-02,
        1.17190179e-02])

In [103]:
q[0]

array([ 0.04647219, -0.13152895, -0.07991247,  0.21365552,  0.24046448,
       -0.16306149,  0.10764529, -0.13924245, -0.08439342,  0.12460081,
       -0.09668627,  0.1034107 , -0.24117738,  0.06613904,  0.16261078,
        0.39023154,  0.01841627, -0.0206131 , -0.13072882, -0.01642854,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ])

In [104]:
R[0]

array([-4.87566555,  1.26889654,  1.69498164, -1.56557684, -1.3433962 ,
        0.30415582,  0.70902853, -0.456333  , -0.04962977, -0.5098901 ,
        1.31409746,  0.81888382,  0.66322264,  0.56026083,  0.17073658,
        0.39114962, -0.50452943,  1.29598487,  0.24746676,  1.95521187])

In [105]:
r[0]

array([ 4.87566555, -0.02986671, -0.01911273,  0.04767314,  0.05293507,
       -0.03528407,  0.02202659, -0.03308594, -0.01671546,  0.02647038,
       -0.01877504,  0.02506043, -0.06460746,  0.01719814,  0.04611032,
        0.10674823,  0.02293828, -0.04776726, -0.01927824,  0.01303765])

In [106]:
np.linalg.cond(A)

13.6427585801428

In [115]:
from sklearn.datasets import make_classification
A = make_classification(n_redundant=2)[0]

In [117]:
modGramSchmidt(A)

(array([[-0.09737497,  0.09537862,  0.02971996, ...,  0.        ,
          0.        ,  0.        ],
        [-0.07022483, -0.02704914,  0.03907363, ...,  0.        ,
          0.        ,  0.        ],
        [-0.08855556,  0.09393345, -0.02578961, ...,  0.        ,
          0.        ,  0.        ],
        ...,
        [-0.01395009, -0.09337805,  0.09688061, ...,  0.        ,
          0.        ,  0.        ],
        [-0.05873064, -0.03484292,  0.03629031, ...,  0.        ,
          0.        ,  0.        ],
        [ 0.09749442,  0.1511321 ,  0.06153027, ...,  0.        ,
          0.        ,  0.        ]]),
 array([[ 1.25402842e+01, -1.17582676e-01, -3.62712552e-02, ...,
         -3.23247561e-02, -6.76076394e-02, -1.24857948e-02],
        [ 0.00000000e+00,  1.25402842e+01, -3.91926569e-02, ...,
         -3.20969023e-02, -5.24252484e-02,  6.91368422e-03],
        [ 0.00000000e+00,  0.00000000e+00,  1.25402842e+01, ...,
         -4.69688453e-03, -3.03682610e-02, -6.83478943e-

In [118]:
spl.qr(A)

(array([[-0.09737497,  0.09318322,  0.04036278, ...,  0.00601613,
          0.0188338 ,  0.00480716],
        [-0.07022483, -0.04160584,  0.05166198, ..., -0.07674264,
         -0.05715277,  0.12446431],
        [-0.08855556,  0.09291069, -0.03050712, ...,  0.06233783,
          0.00761857,  0.12333239],
        ...,
        [-0.01395009, -0.10818324,  0.12375723, ...,  0.78353148,
         -0.04753857,  0.06182819],
        [-0.05873064, -0.04867144,  0.04781594, ..., -0.03358375,
          0.88684753, -0.0066998 ],
        [ 0.09749442,  0.18671707,  0.0754655 , ...,  0.10838481,
          0.01958326,  0.72029271]]),
 array([[12.54028416, -1.83116003,  0.23615759, ..., -4.24043617,
         -0.87010945, -0.64508436],
        [ 0.        , 11.04507278, -0.02478071, ...,  0.06507149,
          0.27801934, -0.40917534],
        [ 0.        ,  0.        ,  9.8555024 , ...,  0.04687404,
         -0.95293927, -0.32504168],
        ...,
        [ 0.        ,  0.        ,  0.        , ...,  