In [1]:
import numpy as np

In [22]:
A = np.matrix([[1,0],[0,1]])

In [23]:
A

matrix([[1, 0],
        [0, 1]])

In [24]:
A.H

matrix([[1, 0],
        [0, 1]])

In [25]:
np.dot(A,A.H)

matrix([[1, 0],
        [0, 1]])

In [26]:
np.dot(A.H,A)

matrix([[1, 0],
        [0, 1]])

In [27]:
np.dot(A,A)

matrix([[1, 0],
        [0, 1]])