In [185]:
import numpy as np
from scipy.linalg import lu

In [186]:
def LU(A):
    '''Performs LU Decomposition with partial pivoting.'''
    
    U=A.copy();
    L=np.zeros([A.shape[1],A.shape[1]])
    
    m=A.shape[0]
    n=A.shape[1]
    
    for k in np.arange(0,m,1):
        P=np.identity(A.shape[1])
        
        # Select pivot row
        row = k+np.argmax(np.abs(U[k:,k]))
        # swap the current and pivot rows
        # pivot P matrix
        temp = P[k,:].copy()
        P[k,:] = P[row,:]
        P[row,:] = temp
        
        U = P@U
        L = P@L
        
        L[k,k]=1
        
        for j in np.arange(k+1,m,1):

            L[j,k] = U[j,k] / U[k,k]
            U[j,k:m] = U[j,k:m] - L[j,k]*U[k,k:m]

    return P,L,U

In [187]:
A=np.array([[2, 1, 1, 1], [4, 3, 3, 1], [8, 7, 9, 5], [6, 7, 9, 8]])
A

array([[2, 1, 1, 1],
       [4, 3, 3, 1],
       [8, 7, 9, 5],
       [6, 7, 9, 8]])

In [188]:
p,l,u = lu(A)

In [189]:
P,L,U=LU(A)

Compare scipy lu (lower case results) and my homegrown LU (upper case results)

In [190]:
L

array([[ 1.        ,  0.        ,  0.        ,  0.        ],
       [ 0.75      ,  1.        ,  0.        ,  0.        ],
       [ 0.5       , -0.28571429,  1.        ,  0.        ],
       [ 0.25      , -0.42857143,  0.33333333,  1.        ]])

In [191]:
l

array([[ 1.        ,  0.        ,  0.        ,  0.        ],
       [ 0.75      ,  1.        ,  0.        ,  0.        ],
       [ 0.5       , -0.28571429,  1.        ,  0.        ],
       [ 0.25      , -0.42857143,  0.33333333,  1.        ]])

In [192]:
U

array([[ 8.        ,  7.        ,  9.        ,  5.        ],
       [ 0.        ,  1.75      ,  2.25      ,  4.25      ],
       [ 0.        ,  0.        , -0.85714286, -0.28571429],
       [ 0.        ,  0.        ,  0.        ,  1.66666667]])

In [193]:
u

array([[ 8.        ,  7.        ,  9.        ,  5.        ],
       [ 0.        ,  1.75      ,  2.25      ,  4.25      ],
       [ 0.        ,  0.        , -0.85714286, -0.28571429],
       [ 0.        ,  0.        ,  0.        ,  1.66666667]])